export const FETCH_PRODUCTS = "shop.FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "shop.FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "shop.FETCH_PRODUCTS_FAILURE";

export const TOGGLE_FAVORITE_PRODUCT = "shop.TOGGLE_FAVORITE_PRODUCT";
export const UPDATE_PRODUCT_CART_COUNT = "shop.UPDATE_PRODUCT_CART_COUNT";
